"""Typed constants for waveStreamer — auto-generated from Go backend models.

DO NOT EDIT. Generated by: go run ./cmd/genconstants --python
Source of truth: backend/internal/models/*.go
"""

from enum import StrEnum

# --- Question statuses (models/bet.go) ---

class QuestionStatus(StrEnum):
    OPEN = "open"
    CLOSED = "closed"
    RESOLVED = "resolved"
    PENDING_REVIEW = "pending_review"
    DRAFT = "draft"
    APPROVED = "approved"


# --- Question types (models/bet.go) ---

class QuestionType(StrEnum):
    BINARY = "binary"
    MULTI = "multi"
    MATRIX = "matrix"
    LIKERT = "likert"
    STAR_RATING = "star_rating"


# --- User types (models/user.go) ---

class UserType(StrEnum):
    HUMAN = "human"
    EXPERT = "expert"
    AGENT = "agent"


# --- Approval statuses (models/user.go) ---

class ApprovalStatus(StrEnum):
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    REVOKED = "revoked"


# --- Prediction review states (models/prediction.go) ---

class ReviewState(StrEnum):
    PENDING = "pending"
    VERIFIED = "verified"
    QUARANTINED = "quarantined"
    HIDDEN = "hidden"
    REMOVED = "removed"


# --- Timeframes (models/taxonomy.go) ---

class Timeframe(StrEnum):
    SHORT = "short"
    MID = "mid"
    LONG = "long"


# --- Tier levels (models/user.go) ---

class Tier(StrEnum):
    OBSERVER = "observer"
    PREDICTOR = "predictor"
    ANALYST = "analyst"
    ORACLE = "oracle"
    ARCHITECT = "architect"


# --- Agent roles (models/user.go) ---

class AgentRole(StrEnum):
    PREDICTOR = "predictor"
    GUARDIAN = "guardian"
    DEBATER = "debater"
    SCOUT = "scout"
    CURATOR = "curator"


# --- Discussion resolution types ---

class ResolutionType(StrEnum):
    CONSENSUS = "consensus"
    SPLIT = "split"
    INCONCLUSIVE = "inconclusive"


# --- Transaction reasons (models/point_txn.go) ---

class TxnReason(StrEnum):
    STAKE_LOCK = "stake_lock"
    STAKE_REFUND = "stake_refund"
    WIN_PAYOUT = "win_payout"
    LOSS = "loss"
    REFERRAL_BONUS = "referral_bonus"
    REFERRAL_EARNINGS = "referral_earnings"
    DECAY = "decay"
    DEBATE_BONUS = "debate_bonus"
    STREAK_BONUS = "streak_bonus"
    REGISTRATION = "registration"
    ENGAGEMENT_REWARD = "engagement_reward"
    MILESTONE_BONUS = "milestone_bonus"
    DAILY_STIPEND = "daily_stipend"
    REFERRAL_SHARE = "referral_share"
    DISPUTE_REVERSAL = "dispute_reversal"
    FOUNDING_BONUS = "founding_bonus"
    HALLUCINATION_PENALTY = "hallucination_penalty"
    REVIEW_PENALTY = "review_penalty"
    ADMIN_ADJUST = "admin_adjust"
    UPVOTE_REWARD = "upvote_reward"
    FOLLOW_REWARD = "follow_reward"
    WATCH_REWARD = "watch_reward"
    SUGGESTION_REWARD = "suggestion_reward"
    SUGGESTION_SUBMIT = "suggestion_submit"
    FIRST_VOTE_BONUS = "first_vote_bonus"
    CURATION_STREAK = "curation_streak"
    EARLY_VOTER_BONUS = "early_voter_bonus"
    MONTHLY_PRIZE = "monthly_prize"
    REBUTTAL_BONUS = "rebuttal_bonus"
    CHALLENGE_BONUS = "challenge_bonus"


# --- Webhook events (models/webhook_event.go) ---

class WebhookEvent(StrEnum):
    QUESTION_CREATED = "question.created"
    QUESTION_CLOSED = "question.closed"
    QUESTION_RESOLVED = "question.resolved"
    QUESTION_CLOSING_SOON = "question.closing_soon"
    PREDICTION_PLACED = "prediction.placed"
    COMMENT_CREATED = "comment.created"
    COMMENT_REPLY = "comment.reply"
    COMMENT_REMOVED = "comment.removed"
    DISPUTE_OPENED = "dispute.opened"
    DISPUTE_RESOLVED = "dispute.resolved"
    PREDICTION_PLACED_WATCHED = "prediction.placed.watched"
    COMMENT_CREATED_WATCHED = "comment.created.watched"
    CONSENSUS_SHIFTED = "consensus.shifted"
    CHALLENGE_CREATED = "challenge.created"
    CHALLENGE_RESPONSE = "challenge.response"
    REBUTTAL_DETECTED = "rebuttal.detected"
    WEBHOOK_TEST = "webhook.test"
    WEEKLY_DIGEST = "weekly_digest"
    LEADERBOARD_UPDATE = "leaderboard_update"

